/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author user
 */
public class admin2 extends javax.swing.JFrame {

    Connection conn= null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form admin2
     */
    public admin2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        option = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Firstname:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, 70, 130, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Lastname:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 120, 130, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(420, 180, 130, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(430, 240, 140, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 300, 100, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Options:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(450, 360, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("PhoneNo:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(430, 420, 120, 29);
        jPanel1.add(fname);
        fname.setBounds(600, 70, 190, 30);
        jPanel1.add(lname);
        lname.setBounds(600, 120, 190, 30);
        jPanel1.add(uname);
        uname.setBounds(600, 180, 190, 30);

        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });
        jPanel1.add(phone);
        phone.setBounds(600, 420, 190, 30);
        jPanel1.add(email);
        email.setBounds(600, 300, 190, 30);
        jPanel1.add(option);
        option.setBounds(600, 360, 190, 30);
        jPanel1.add(pass);
        pass.setBounds(600, 240, 190, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 500, 120, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(620, 500, 120, 31);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 0, 0);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Please Input Firstname to DELETE");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(760, 510, 240, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(560, 560, 80, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\UKULIMAMIWA\\JAVA\\videoblocks-sugar-cane-plantation-in-sunset-in-brazil-aerial-view-canavial_r3xsbevdje_thumbnail-full01.png")); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 1110, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        this.setExtendedState(this.getExtendedState()| JFrame.MAXIMIZED_BOTH);
    } 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String Firstname= fname.getText();
        String Lastname= lname.getText();
        String Username= uname.getText();
        String Password= pass.getText();
        String Email= email.getText();
        String Option= option.getText();
        String PhoneNumber = phone.getText();
        if (Firstname.equals("")){
            JOptionPane.showMessageDialog(null, "please input First name");
        
        if (Lastname.equals("")){
            JOptionPane.showMessageDialog(null, "please input Last name");
        }
        if (Username.equals("")){
            JOptionPane.showMessageDialog(null, "please input Username");
        }
        if (Password.equals("")){
            JOptionPane.showMessageDialog(null, "please input Password");
        }
        if (Email.equals("")){
            JOptionPane.showMessageDialog(null, "please input Location");
        }
        if (Option.equals("")){
            JOptionPane.showMessageDialog(null, "please input Email");
        }
        if (PhoneNumber.equals("")){
            JOptionPane.showMessageDialog(null, "please input Your Phone Number");
        }
        }
        else {
            JOptionPane.showMessageDialog(null, "Validation successful");
        }
        
        try{
           String query="INSERT INTO userdata(Firstname, Lastname, Username, Password, Email, Options, PhoneNo) VALUES (?,?,?,?,?,?,?)";
	 conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/Login?zeroDateTimeBehavior=convertToNull","root","");
         
           pst = conn.prepareStatement(query);
         pst.setString(1,fname.getText());
	pst.setString(2,lname.getText());
	pst.setString(3,uname.getText());
	pst.setString(4,pass.getText());
        pst.setString(5,email.getText());
        pst.setString(7,phone.getText());
        pst.setString(6,option.getText());   
					
	pst.executeUpdate();
	JOptionPane.showMessageDialog(null," Data is Save Succeefully"); 
        pst.close();
             
				 
        }
        catch(Exception e){
            
           JOptionPane.showMessageDialog(null, e);
             
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try{
           String query="DELETE FROM userdata WHERE Firstname = ?";
	 conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/Login?zeroDateTimeBehavior=convertToNull","root","");
         
           pst = conn.prepareStatement(query);
         pst.setString(1,fname.getText());
     
					
	pst.executeUpdate();
	JOptionPane.showMessageDialog(null," Data is deleted Succeefully"); 
        pst.close();
				 
        }
        catch(Exception e){
            
           JOptionPane.showMessageDialog(null, e);
             
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c== evt.VK_BACK_SPACE) || c==evt.VK_DELETE)){
        getToolkit().beep();
            evt.consume();
    }//GEN-LAST:event_phoneKeyTyped
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide();
        admin rgf = new admin();
        rgf.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField option;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
