
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Fertiliz extends javax.swing.JFrame {

    Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
    /**
     * Creates new form Fertiliz
     */
    public Fertiliz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        am = new javax.swing.JTextField();
        im = new javax.swing.JTextField();
        fert = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(750, 610, 100, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Black");
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 60, 63, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("This is associated with\nhigh level of organic matter.\nIt may have bad drainage,low\npH and high denitrification.\nFarmer is adviced to use");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 100, 220, 110);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("BlackClay");
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 60, 90, 23);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("It is associated with poor \ndrainage and dificult in\nduring ploughing.Use");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(370, 100, 220, 100);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("White/Pale");
        jPanel1.add(jButton4);
        jButton4.setBounds(760, 50, 100, 23);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("The Iron and Manganise particles\nhave been swept away due to\npoor drainage orlarge amount\nof rain.");
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(690, 100, 220, 100);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Red");
        jPanel1.add(jButton5);
        jButton5.setBounds(1100, 50, 57, 23);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("Indicates good drainage and soil\nrich in Iron and is oxidised\ndue to lot of oxygen in soil\nhigh phosphorous and low\nwater content.Use");
        jScrollPane4.setViewportView(jTextArea4);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(1010, 100, 210, 96);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("YellowBrown");
        jPanel1.add(jButton6);
        jButton6.setBounds(110, 230, 111, 23);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("Poor drainage Iron in it is\nin hydrate form has\nmoderate phosphorus and\nlow water content.");
        jScrollPane5.setViewportView(jTextArea5);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(70, 270, 190, 100);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Brown");
        jPanel1.add(jButton7);
        jButton7.setBounds(460, 230, 73, 23);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("Moderate organic matterand\nIron Oxides. has low moderate\nphosphorusand low water \ncontent.");
        jScrollPane6.setViewportView(jTextArea6);

        jPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(380, 270, 220, 96);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Grey/Green");
        jPanel1.add(jButton8);
        jButton8.setBounds(1040, 220, 110, 23);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setText("Very poor drainage and water\nlogging.Emites methane that \nis hazard, has high \ndenitrification.");
        jScrollPane7.setViewportView(jTextArea7);

        jPanel1.add(jScrollPane7);
        jScrollPane7.setBounds(1010, 260, 190, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Type:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 450, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Fertilizer:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 580, 86, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Mode Of Input:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 530, 150, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Amount Needed per Hacter:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 490, 260, 22);
        jPanel1.add(type);
        type.setBounds(430, 450, 170, 30);
        jPanel1.add(am);
        am.setBounds(430, 490, 170, 30);
        jPanel1.add(im);
        im.setBounds(430, 530, 170, 30);
        jPanel1.add(fert);
        fert.setBounds(430, 580, 170, 30);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(670, 500, 80, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Please Input The Soil Color To Search");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 400, 460, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\UKULIMAMIWA\\JAVA\\videoblocks-sugar-cane-plantation-in-sunset-in-brazil-aerial-view-canavial_r3xsbevdje_thumbnail-full01.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(1920, 1200));
        jLabel2.setMinimumSize(new java.awt.Dimension(1920, 1200));
        jLabel2.setPreferredSize(new java.awt.Dimension(1920, 1200));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState()| JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
        Farmer rgf = new Farmer();
        rgf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String t = type.getText();
        
         try{
            
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Login?zeroDateTimeBehavior=convertToNull","root","");
        pst = conn.prepareStatement("SELECT *FROM fertilizer where Type = ?");
        pst.setString(1, t);
        rs = pst.executeQuery();
        while (rs.next()){
        am.setText(rs.getString("AmtPerHaInBags"));
        im.setText(rs.getString("InputMode"));
        fert.setText(rs.getString("Fertilizer"));
        
        
        }
        
         }catch(Exception ex){
         JOptionPane.showMessageDialog(null, ex);
         }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fertiliz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fertiliz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fertiliz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fertiliz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fertiliz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField am;
    private javax.swing.JTextField fert;
    private javax.swing.JTextField im;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
