
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class harvest extends javax.swing.JFrame {

    /**
     * Creates new form harvest
     */
    public harvest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jComboBox15 = new javax.swing.JComboBox<>();
        jComboBox16 = new javax.swing.JComboBox<>();
        jComboBox17 = new javax.swing.JComboBox<>();
        jComboBox18 = new javax.swing.JComboBox<>();
        jComboBox19 = new javax.swing.JComboBox<>();
        jComboBox20 = new javax.swing.JComboBox<>();
        jButton21 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Malaba Region");
        jPanel2.add(jButton1);
        jButton1.setBounds(120, 180, 140, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Chwele Region");
        jPanel2.add(jButton2);
        jButton2.setBounds(120, 260, 140, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Ngoli Region");
        jPanel2.add(jButton3);
        jButton3.setBounds(120, 340, 140, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Bukembe Region");
        jPanel2.add(jButton4);
        jButton4.setBounds(120, 430, 140, 23);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Sangalo Region");
        jPanel2.add(jButton5);
        jButton5.setBounds(330, 180, 140, 23);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Misikhu Region");
        jPanel2.add(jButton6);
        jButton6.setBounds(330, 260, 140, 23);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Lugulu Region");
        jPanel2.add(jButton7);
        jButton7.setBounds(330, 340, 140, 23);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Kimilili Region");
        jPanel2.add(jButton8);
        jButton8.setBounds(330, 430, 140, 23);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("MayanjaRegion");
        jPanel2.add(jButton9);
        jButton9.setBounds(540, 180, 150, 23);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("Nzoia Region");
        jPanel2.add(jButton10);
        jButton10.setBounds(540, 260, 150, 23);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setText("Mumias Region");
        jPanel2.add(jButton11);
        jButton11.setBounds(540, 340, 150, 23);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("Kanduyi Region");
        jPanel2.add(jButton12);
        jButton12.setBounds(540, 430, 150, 23);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.setText("Mulaa Region");
        jPanel2.add(jButton13);
        jButton13.setBounds(800, 180, 150, 23);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton14.setText("Kimwanga Region");
        jPanel2.add(jButton14);
        jButton14.setBounds(800, 260, 150, 23);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton15.setText("Bukhungu Region");
        jPanel2.add(jButton15);
        jButton15.setBounds(800, 350, 150, 23);

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton16.setText("Mukhuyu Region");
        jPanel2.add(jButton16);
        jButton16.setBounds(800, 430, 150, 23);

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton17.setText("Kimaeti Region");
        jPanel2.add(jButton17);
        jButton17.setBounds(1060, 190, 140, 23);

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton18.setText("Port Region");
        jPanel2.add(jButton18);
        jButton18.setBounds(1060, 270, 140, 23);

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton19.setText("Busia Region");
        jButton19.setToolTipText("");
        jPanel2.add(jButton19);
        jButton19.setBounds(1060, 350, 140, 23);

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton20.setText("Mt Elgon Region");
        jPanel2.add(jButton20);
        jButton20.setBounds(1060, 430, 140, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "August", "September", "October" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(120, 220, 140, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "March", "May", "June" }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(120, 300, 140, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "March", "June" }));
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(120, 390, 140, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "June", "November", "December" }));
        jPanel2.add(jComboBox4);
        jComboBox4.setBounds(120, 470, 140, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "August", "October", "December" }));
        jPanel2.add(jComboBox5);
        jComboBox5.setBounds(330, 220, 140, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "June", "July", "August" }));
        jPanel2.add(jComboBox6);
        jComboBox6.setBounds(330, 300, 140, 20);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "March", "May", "July" }));
        jPanel2.add(jComboBox7);
        jComboBox7.setBounds(330, 390, 140, 20);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "May", "August", "October" }));
        jPanel2.add(jComboBox8);
        jComboBox8.setBounds(330, 470, 140, 20);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "March", "November", "December" }));
        jPanel2.add(jComboBox9);
        jComboBox9.setBounds(546, 220, 140, 20);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "March", "September" }));
        jPanel2.add(jComboBox10);
        jComboBox10.setBounds(540, 300, 150, 20);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "February", "April", "July" }));
        jPanel2.add(jComboBox11);
        jComboBox11.setBounds(540, 390, 150, 20);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "March", "April", "August" }));
        jPanel2.add(jComboBox12);
        jComboBox12.setBounds(540, 470, 150, 20);

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "February", "May", "November" }));
        jComboBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox13ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox13);
        jComboBox13.setBounds(800, 220, 150, 20);

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "April", "May", "November" }));
        jPanel2.add(jComboBox14);
        jComboBox14.setBounds(800, 300, 150, 20);

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "July", "December" }));
        jPanel2.add(jComboBox15);
        jComboBox15.setBounds(800, 390, 150, 20);

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "May", "July", "November" }));
        jComboBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox16ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox16);
        jComboBox16.setBounds(800, 470, 150, 20);

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "December", "November", "January" }));
        jPanel2.add(jComboBox17);
        jComboBox17.setBounds(1060, 230, 140, 20);

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "April", "June", "September" }));
        jPanel2.add(jComboBox18);
        jComboBox18.setBounds(1060, 310, 140, 20);

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "June", "August", "October" }));
        jPanel2.add(jComboBox19);
        jComboBox19.setBounds(1060, 390, 140, 20);

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "May", "August", "October" }));
        jPanel2.add(jComboBox20);
        jComboBox20.setBounds(1060, 470, 140, 20);

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton21.setText("Back");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton21);
        jButton21.setBounds(720, 560, 65, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\UKULIMAMIWA\\JAVA\\videoblocks-sugar-cane-plantation-in-sunset-in-brazil-aerial-view-canavial_r3xsbevdje_thumbnail-full01.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1900, 1200));
        jLabel1.setMinimumSize(new java.awt.Dimension(1900, 1200));
        jLabel1.setPreferredSize(new java.awt.Dimension(1900, 1200));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1900, 1200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1217, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState()| JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox13ActionPerformed

    private void jComboBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox16ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        this.hide();
        Farmer rgf = new Farmer();
        rgf.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(harvest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(harvest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(harvest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(harvest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new harvest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
