/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class harvest2 extends javax.swing.JFrame {

    /**
     * Creates new form harvest2
     */
    public harvest2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jComboBox13 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jComboBox15 = new javax.swing.JComboBox<>();
        jComboBox16 = new javax.swing.JComboBox<>();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jComboBox17 = new javax.swing.JComboBox<>();
        jComboBox18 = new javax.swing.JComboBox<>();
        jComboBox19 = new javax.swing.JComboBox<>();
        jComboBox20 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Mayanja Region");
        jPanel1.add(jButton1);
        jButton1.setBounds(610, 120, 130, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Nzoia Region");
        jPanel1.add(jButton2);
        jButton2.setBounds(610, 200, 130, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Mumias Region");
        jPanel1.add(jButton3);
        jButton3.setBounds(610, 290, 130, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Kanduyi Region");
        jPanel1.add(jButton4);
        jButton4.setBounds(610, 390, 130, 23);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Kimaeti Region");
        jPanel1.add(jButton5);
        jButton5.setBounds(1060, 120, 140, 23);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Kimwanga Region");
        jPanel1.add(jButton6);
        jButton6.setBounds(820, 200, 140, 23);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Bukhungu Region");
        jPanel1.add(jButton7);
        jButton7.setBounds(820, 280, 140, 23);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Mukhuyu Region");
        jPanel1.add(jButton8);
        jButton8.setBounds(820, 380, 140, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "March", "November", "December" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(610, 160, 130, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "March", "September" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(610, 250, 130, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "February", "April", "July" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(610, 340, 130, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "May", "July", "November" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(820, 430, 140, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "February", "May", "November" }));
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(820, 160, 140, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "April", "May", "November" }));
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(820, 240, 140, 20);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "July", "December" }));
        jPanel1.add(jComboBox7);
        jComboBox7.setBounds(820, 330, 140, 20);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "March", "April", "August" }));
        jPanel1.add(jComboBox8);
        jComboBox8.setBounds(610, 440, 130, 20);

        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(700, 520, 100, 23);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("Mulaa Region");
        jPanel1.add(jButton10);
        jButton10.setBounds(820, 120, 140, 23);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setText("Port Region");
        jPanel1.add(jButton11);
        jButton11.setBounds(1060, 200, 140, 23);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("Busia Region");
        jPanel1.add(jButton12);
        jButton12.setBounds(1060, 280, 140, 23);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.setText("Mt Elgon Region");
        jPanel1.add(jButton13);
        jButton13.setBounds(1060, 380, 140, 23);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "December", "November", "January" }));
        jPanel1.add(jComboBox9);
        jComboBox9.setBounds(1060, 160, 140, 20);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "April", "June", "September" }));
        jPanel1.add(jComboBox10);
        jComboBox10.setBounds(1060, 240, 140, 20);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "June", "August", "October" }));
        jPanel1.add(jComboBox11);
        jComboBox11.setBounds(1060, 330, 140, 20);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "May", "August", "October" }));
        jPanel1.add(jComboBox12);
        jComboBox12.setBounds(1060, 430, 140, 20);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton14.setText("Sangalo Region");
        jPanel1.add(jButton14);
        jButton14.setBounds(380, 120, 130, 23);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton15.setText("Misikhu Region");
        jPanel1.add(jButton15);
        jButton15.setBounds(380, 200, 130, 23);

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton16.setText("Lugulu Region");
        jPanel1.add(jButton16);
        jButton16.setBounds(380, 290, 130, 23);

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton17.setText("Kimilili Region");
        jPanel1.add(jButton17);
        jButton17.setBounds(380, 390, 130, 23);

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "August", "October", "December" }));
        jPanel1.add(jComboBox13);
        jComboBox13.setBounds(380, 160, 130, 20);

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "June", "July", "August" }));
        jPanel1.add(jComboBox14);
        jComboBox14.setBounds(380, 250, 130, 20);

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "March", "May", "July" }));
        jPanel1.add(jComboBox15);
        jComboBox15.setBounds(380, 340, 130, 20);

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "May", "August", "October" }));
        jPanel1.add(jComboBox16);
        jComboBox16.setBounds(380, 440, 130, 20);

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton18.setText("Malaba Region");
        jPanel1.add(jButton18);
        jButton18.setBounds(160, 120, 130, 23);

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton19.setText("Chwele Region");
        jPanel1.add(jButton19);
        jButton19.setBounds(160, 200, 130, 23);

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton20.setText("Ngoli Region");
        jPanel1.add(jButton20);
        jButton20.setBounds(160, 290, 130, 23);

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton21.setText("Bukembe Region");
        jPanel1.add(jButton21);
        jButton21.setBounds(160, 390, 130, 23);

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "August", "September", "October" }));
        jPanel1.add(jComboBox17);
        jComboBox17.setBounds(160, 160, 130, 20);

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "March", "May", "June" }));
        jPanel1.add(jComboBox18);
        jComboBox18.setBounds(160, 250, 130, 20);

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "March", "June" }));
        jPanel1.add(jComboBox19);
        jComboBox19.setBounds(160, 340, 130, 20);

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "June", "November", "December", "" }));
        jPanel1.add(jComboBox20);
        jComboBox20.setBounds(160, 440, 130, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\JAVA\\videoblocks-sugar-cane-plantation-in-sunset-in-brazil-aerial-view-canavial_r3xsbevdje_thumbnail-full01.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1200));
        jLabel1.setMinimumSize(new java.awt.Dimension(1920, 1200));
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1200));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         this.hide();
        admin rgf = new admin();
        rgf.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(harvest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(harvest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(harvest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(harvest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new harvest2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
