
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class plough extends javax.swing.JFrame {

    Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
    /**
     * Creates new form plough
     */
    public plough() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        dn = new javax.swing.JTextField();
        fc = new javax.swing.JTextField();
        r = new javax.swing.JTextField();
        np = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dd = new javax.swing.JTextField();
        sl = new javax.swing.JTextField();
        phn = new javax.swing.JTextField();
        loc = new javax.swing.JTextField();
        mot = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Farmer ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(810, 180, 131, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Driver Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(790, 230, 159, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Fuel Consumption:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(730, 280, 224, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Repairs:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(860, 340, 98, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("NumberPlate:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(790, 400, 166, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("PhoneNo:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(840, 460, 120, 29);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(990, 180, 160, 30);
        jPanel1.add(dn);
        dn.setBounds(990, 230, 160, 30);
        jPanel1.add(fc);
        fc.setBounds(990, 280, 160, 30);
        jPanel1.add(r);
        r.setBounds(990, 340, 160, 30);
        jPanel1.add(np);
        np.setBounds(990, 400, 160, 30);
        jPanel1.add(pn);
        pn.setBounds(990, 460, 160, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(950, 540, 80, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Pleas Input Your ID To Search Farmer's Data");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(870, 130, 330, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("ID:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(290, 200, 39, 29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Size Of Land:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(170, 240, 157, 29);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Phone Number:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(140, 290, 190, 29);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Location:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(210, 350, 112, 29);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Month:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(230, 410, 90, 29);
        jPanel1.add(dd);
        dd.setBounds(400, 200, 160, 30);

        sl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slActionPerformed(evt);
            }
        });
        jPanel1.add(sl);
        sl.setBounds(400, 250, 160, 30);
        jPanel1.add(phn);
        phn.setBounds(400, 300, 160, 30);
        jPanel1.add(loc);
        loc.setBounds(400, 350, 160, 30);
        jPanel1.add(mot);
        mot.setBounds(400, 410, 160, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(310, 500, 79, 25);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Please Input Your ID To Search");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(320, 140, 300, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\UKULIMAMIWA\\JAVA\\videoblocks-sugar-cane-plantation-in-sunset-in-brazil-aerial-view-canavial_r3xsbevdje_thumbnail-full01.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(1900, 1200));
        jLabel2.setMinimumSize(new java.awt.Dimension(1900, 1200));
        jLabel2.setPreferredSize(new java.awt.Dimension(1900, 1200));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1900, 1200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState()| JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Id = id.getText();
        
        try{
            
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Login?zeroDateTimeBehavior=convertToNull","root","");
        pst = conn.prepareStatement("SELECT *FROM tractor where FarmerID = ?");
        pst.setString(1, Id);
        rs = pst.executeQuery();
        while (rs.next()){
        dn.setText(rs.getString("DriverName"));
        fc.setText(rs.getString("FuelConsum"));
        r.setText(rs.getString("Repairs"));
        np.setText(rs.getString("NumberPlate"));
        pn.setText(rs.getString("PhoneNo"));
        
        
        }
        
         }catch(Exception ex){
         JOptionPane.showMessageDialog(null, ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void slActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String u = dd.getText();
        
        try{
            
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Login?zeroDateTimeBehavior=convertToNull","root","");
        pst = conn.prepareStatement("SELECT *FROM plough where ID = ?");
        pst.setString(1, u);
        rs = pst.executeQuery();
        while (rs.next()){
        sl.setText(rs.getString("SizeOfLand"));
        phn.setText(rs.getString("PhoneNo"));
        loc.setText(rs.getString("Location"));
        mot.setText(rs.getString("Month"));
        
        
        
        }
        
         }catch(Exception ex){
         JOptionPane.showMessageDialog(null, ex);
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plough.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plough.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plough.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plough.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new plough().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dd;
    private javax.swing.JTextField dn;
    private javax.swing.JTextField fc;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loc;
    private javax.swing.JTextField mot;
    private javax.swing.JTextField np;
    private javax.swing.JTextField phn;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField r;
    private javax.swing.JTextField sl;
    // End of variables declaration//GEN-END:variables
}
